name: Release Branches
on:
  push:
    branches:
      - 'release/**'


jobs:
  compile_test:
    uses: ./.github/workflows/maven.yml
  tag:
    name: "Tag Release"
    runs-on: ubuntu-latest
    needs: compile_test
    steps:
      - name: Get App Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APP_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v2
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: 'maven'
      - name: Set version var
        id: version
        run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      - name: Create and push tag
        run: |
          git tag "v${{ steps.version.outputs.version }}"
          git push origin "v${{ steps.version.outputs.version }}"
